[package]
authors = ["Jonas Platte <mail@jonasplatte.de>"]
name = "ruma-gtk"
version = "0.1.0"

[dependencies]
futures = "0.1.14"
gio = "0.1.3"
hyper = "0.11.1"
tokio-core = "0.1.8"
url = "1.5.1"

[dependencies.gtk]
features = ["v3_12"]
version = "0.1.3"

[dependencies.ruma-client]
git = "https://github.com/jplatte/ruma-client.git"
